# Alacritty Configuration Example
# Description: This configuration customizes the appearance of the Alacritty terminal emulator.
# It includes a custom color scheme and various settings to enhance the terminal experience.
# Feel free to modify the configurations according to your preference.

# Indexed colors for extending the color palette.
[[colors.indexed_colors]]
color = "#FAB387"  # Peachy color for additional accents.
index = 16

[[colors.indexed_colors]]
color = "#F5E0DC"  # Soft pink for additional accents.
index = 17

# Bright color variants for high visibility.
[colors.bright]
black = "#585B70"  # Slate gray for bright black.
blue = "#89B4FA"   # Light blue for a vibrant look.
cyan = "#94E2D5"   # Turquoise for bright cyan.
green = "#A6E3A1"  # Soft green for a fresh appearance.
magenta = "#F5C2E7" # Pale pink for bright magenta.
red = "#F38BA8"    # Soft red for attention.
white = "#A6ADC8"  # Cool gray for bright white.
yellow = "#F9E2AF" # Muted yellow for warmth.

# Cursor appearance customization.
[colors.cursor]
cursor = "#F5E0DC" # Soft pink cursor color for visibility.
text = "#1E1E2E"   # Dark background text color for contrast.

# Dim color variants for subdued appearance.
[colors.dim]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

# Hint colors for search and selection feedback.
[colors.hints.end]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.hints.start]
background = "#F9E2AF"
foreground = "#1E1E2E"

# Standard color set for normal use.
[colors.normal]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

# Primary colors including background and foreground settings.
[colors.primary]
background = "#1E1E2E" # Dark mode background for less eye strain.
bright_foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
foreground = "#CDD6F4" # Main text color for readability.

# Search and selection highlights for usability.
[colors.search.focused_match]
background = "#A6E3A1"
foreground = "#1E1E2E"

[colors.search.matches]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.selection]
background = "#F5E0DC"
text = "#1E1E2E"

# VI mode cursor appearance to distinguish modes.
[colors.vi_mode_cursor]
cursor = "#B4BEFE"
text = "#1E1E2E"

# Font settings including typeface and size for clarity.
[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font Propo"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font SemBd"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

# Window appearance and behavior settings.
[window]
decorations = "none" # For a clean, distraction-free environment.

[window.dimensions]
columns = 100
lines = 24

[window.padding]
x = 20
y = 20

# Default shell program setup.
[shell]
program = "/usr/bin/fish"
args = ["-c", "tmux attach || tmux new"]

